apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-ms
  labels:
    app: gateway-ms
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: gateway-ms
  template:
    metadata:
      labels:
        app: gateway-ms
    spec:
      containers:
        - name: gateway-ms
          image: lordbyron.azurecr.io/gateway-ms:v1
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: CONFIG_URI
              valueFrom:
                secretKeyRef:
                  name: byron-secret
                  key: config-uri
            - name: CONFIG_ENABLED
              valueFrom:
                secretKeyRef:
                  name: byron-secret
                  key: config-enabled
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-ms-service
spec:
  selector:
    app: gateway-ms
  ports:
    - protocol: TCP
      port: 8080

